### ISSUE TITLE
WebP support

### ISSUE THREAD

**Issue by daybugging** [fundevogel/fundevogel.de#16]
Hey there,
since you are very into performance, why not go for WebP support?

**Comment by S1SYPHOS** [comment]
That's a good idea, had thought about it before. Feel free to open a PR on how to integrate WebP generation into the existing workflow - didn't have much time back in the days to look for / write a plugin for `gulp` / `gulp-imagemin`

// Edit:
https://github.com/imagemin/imagemin-webp

**Comment by S1SYPHOS** [comment]
**Update:**
Seems like I have to write an extension if I want WebP support for images uploaded from Kirby's panel, this library might provide a good starting point:
https://github.com/rosell-dk/webp-convert

Also, after converting images to `.webp`, adding this `.htaccess` directive will replace them if the format is supported by the browser:
https://github.com/vincentorback/WebP-images-with-htaccess

**Comment by S1SYPHOS** [comment]
`kirby-webp` is [out now](https://github.com/S1SYPHOS/kirby-webp), plus I added WebP generation to the workflow with [this commit](https://github.com/two-brain/fundevogel.de/commit/639427868c7b29dbdcd04c30f62d5b467359bbd4). As soon as it lands in this repository as submodule, this will be closed.

Thanks again for the suggestion :+1:

**Comment by S1SYPHOS** [comment]
For Kirby v3, I might use @hashandsalt's [WebP plugin](https://github.com/HashandSalt/kirby3-webp), be sure to check it out :koala: 

.. or maybe I'll come up with my own solution :dancer: 
Cheers!

**Comment by S1SYPHOS** [comment]
This has been implemented, thanks for your patience.
