### ISSUE TITLE
CSP-related error: document.currentScript.setAttribute

### ISSUE THREAD

**Issue by daybugging** [fundevogel/fundevogel.de#20]
??

**Comment by S1SYPHOS** [comment]
Seems like you are [not the only one](https://github.com/nico3333fr/CSP-useful/blob/master/csp-wtf/not-explained.md#documentcurrentscriptsetattribute) encountering (and being confused about) this - anywhoozle, as this doesn't have any known impact, I'll close this issue.

Thanks for mentioning it, anyway!
