### ISSUE TITLE
idea: nonce for inline-style

### ISSUE THREAD

**Issue by daybugging** [fundevogel/fundevogel.de#21]
howdy,
strangely when looking through this, there seem to be nonces being generated, but not applied to some stylesheets included by what seems to be the slider plugin. I think they integrated something a while ago, maybe you could give it a try or I'll make a PR?

cya

**Comment by S1SYPHOS** [comment]
Since CSP isn't a top priority, this will have to wait until there's progress with `tiny-slider`.

**Comment by S1SYPHOS** [comment]
Moved to #24
