### ISSUE TITLE
mobile header nav overlap desktop header nav

### ISSUE THREAD

**Issue by replicant64** [fundevogel/fundevogel.de#48]
Hello,
one other thing i notice that header nav on desktop seems overlapping with normal menu, so all links are shop-links? on mac with firefox that is, chrome not!

**Comment by S1SYPHOS** [comment]
Can't reproduce this, sorry.

// Edit: I was able to, eventually. I'm on it.

**Comment by replicant64** [comment]
Thx man, appreciate this

**Comment by replicant64** [comment]
It seems gone now, did you do something already?

**Comment by replicant64** [comment]
It seems no problem now, you fixed it, yes?

**Comment by replicant64** [comment]
No still there

**Comment by S1SYPHOS** [comment]
I will fix it when redesigning the entire site header as this only affects users of old(er) Safari versions.

It might be reasonable though to set `display: hidden` for the time being .. thanks for staying on top of this!

**Comment by replicant64** [comment]
How's that coming?

**Comment by S1SYPHOS** [comment]
It needs further testing, but so far results are promising :P

**Comment by S1SYPHOS** [comment]
If you'd like, we're expecting to go live tonight, feel free to test and send your feedback!

It's working for me on recent Safari versions, but who knows ..

**Comment by S1SYPHOS** [comment]
As I deployed the changes last night, I'd be happy to hear from you, as it should be fixed now ..

**Comment by S1SYPHOS** [comment]
I'm closing this since it seems fixed now on iOS and Safari.

**Comment by replicant64** [comment]
Seem is alright now, good one there!
