### ISSUE TITLE
new icons

### ISSUE THREAD

**Issue by daybugging** [fundevogel/fundevogel.de#8]
hey there,
cool site, but just one thing: with the headlines being sketchy and to some extent 'childish' (in a good way), the contact icons are the exact opposite. maybe there's some potential creating something new there, you know what I mean?

Have a good day, Sir!

**Comment by S1SYPHOS** [comment]
That's actually true, thanks for the hint.
I'll look into it!

**Comment by daybugging** [comment]
This looks nice!
